name: flutter_tokbox_plugin
description: flutter_tokbox_plugin
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_opentok: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lab.flutter_tokbox_plugin
        pluginClass: FlutterTokboxPlugin
      ios:
        pluginClass: FlutterTokboxPlugin


