name: flutter_tokbox_plugin
description: flutter_tokbox_plugin
version: 0.0.3
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.2
  json_serializable: ^3.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lab.flutter_tokbox_plugin
        pluginClass: FlutterTokboxPlugin
      ios:
        pluginClass: FlutterOpentokPlugin


